const temas = {
    "adjetivos": "Adjetivos",
    "algo macio": "Algo macio",
    "algo que dá medo": "Algo que dá medo",
    "alimento vegano": "Alimento vegano",
    "alimentos": "Alimentos",
    "alimentos saudáveis": "Alimentos saudáveis",
    "animais": "Animais",
    "animais aquáticos": "Animais aquáticos",
    "animais imaginários": "Animais imaginários",
    "animais voadores": "Animais voadores",
    "ao ar livre": "Ao ar livre",
    "atividades perigosas": "Atividades perigosas",
    "aves": "Aves",
    "bebidas": "Bebidas",
    "cantores ou bandas": "Cantores ou bandas",
    "casados tem": "Casados tem",
    "cidades": "Cidades",
    "cobertura de pizza": "Cobertura de pizza",
    "coisas que mães falam": "Coisas que mães falam",
    "cores": "Cores",
    "cosméticos e produtos de higiene pessoal": "Cosméticos e produtos de higiene pessoal",
    "desejos para fazer": "Desejos para fazer",
    "doces": "Doces",
    "doenças ou enfermidades": "Doenças ou enfermidades",
    "é bom no verão": "É bom no verão",
    "emoções": "Emoções",
    "esportes": "Esportes",
    "eventos históricos": "Eventos históricos",
    "ferramentas": "Ferramentas",
    "filmes, programas ou desenho": "Filmes, programas ou desenho",
    "formas": "Formas",
    "frutas": "Frutas",
    "insetos": "Insetos",
    "invenções que mudaram o mundo": "Invenções que mudaram o mundo",
    "mamíferos": "Mamíferos",
    "medos": "Medos",
    "minha sogra é": "Minha sogra é",
    "nome de animais de estimação": "Nome de animais de estimação",
    "nome de meninas": "Nome de meninas",
    "nome de meninos": "Nome de meninos",
    "números": "Números",
    "o que cheira bem": "O que cheira bem",
    "o que cheira mal": "O que cheira mal",
    "o que fará você ser demitido": "O que fará você ser demitido",
    "o que você pode chutar": "O que você pode chutar",
    "objetos": "Objetos",
    "objetos pequenos": "Objetos pequenos",
    "onde você não gostaria de dormir": "Onde você não gostaria de dormir",
    "países": "Países",
    "partes do corpo": "Partes do corpo",
    "personagens": "Personagens",
    "plantas, flores ou árvores": "Plantas, flores ou árvores",
    "pratos típicos": "Pratos típicos",
    "profissões": "Profissões",
    "razões para comemorar": "Razões para comemorar",
    "répteis": "Répteis",
    "sabores de sorvete": "Sabores de sorvete",
    "sobremesas": "Sobremesas",
    "super poderes": "Super poderes",
    "super-heróis": "Super-heróis",
    "tem na bolsa de viagem": "Tem na bolsa de viagem",
    "tem na cozinha": "Tem na cozinha",
    "tem na escola": "Tem na escola",
    "tem na fazenda": "Tem na fazenda",
    "tem na floresta": "Tem na floresta",
    "tem na geladeira": "Tem na geladeira",
    "tem na padaria": "Tem na padaria",
    "tem na praia": "Tem na praia",
    "tem no acampamento": "Tem no acampamento",
    "tem no aeroporto": "Tem no aeroporto",
    "tem no bar": "Tem no bar",
    "tem no café da manhã": "Tem no café da manhã",
    "tem no carro": "Tem no carro",
    "tem no casamento": "Tem no casamento",
    "tem no cemitério": "Tem no cemitério",
    "tem no cinema": "Tem no cinema",
    "tem no circo": "Tem no circo",
    "tem no escritório": "Tem no escritório",
    "tem no hospital": "Tem no hospital",
    "tem no museu": "Tem no museu",
    "tem no natal": "Tem no natal",
    "tem no piquenique": "Tem no piquenique",
    "tem no quarto": "Tem no quarto",
    "tem no quintal ou jardim": "Tem no quintal ou jardim",
    "temperos": "Temperos",
    "típico de minas gerais": "Típico de Minas Gerais",
    "um lugar": "Um lugar",
    "utensílios e eletrodomésticos": "Utensílios e eletrodomésticos",
    "vegetais": "Vegetais",
    "veículos": "Veículos"
};
